package Rust::mysql;

# This file is automatically generated by plbindgen.
# Changes to this file will be lost if it is regenerated.

use FFI::Platypus 2.00;
use FFI::Platypus::Lang::C;
use FFI::Platypus::Lang::Rust;
use FFI::CheckLib qw( find_lib_or_die );
use File::Basename qw( dirname );
use Exporter qw( import );

our @EXPORT = qw( );
our %EXPORT_TAGS = ( all => \@EXPORT );

BEGIN {
    # FIXME: FFI::Platypus::Lang::Rust doesn't have enum.
    my $c_map = FFI::Platypus::Lang::C->native_type_map;
    my $rust_map = FFI::Platypus::Lang::Rust->native_type_map;
    $rust_map->{$_} = $c_map->{$_} for 'enum', 'senum';
    *FFI::Platypus::Lang::Rust::native_type_map = sub { $rust_map };
}

our $VERSION = '0.1.0';

my $ffi = FFI::Platypus->new( api => 2, lang => 'Rust' );
$ffi->bundle;


$ffi->type(enum => 'ErrorCode');

use constant NoError => 0;
use constant Utf8Error => 1;
use constant UrlError => 2;
use constant ConnectionError => 3;
use constant PrepareError => 4;
use constant TransactionError => 5;
push @{ $EXPORT_TAGS{all} }, 'NoError', 'Utf8Error', 'UrlError', 'ConnectionError', 'PrepareError', 'TransactionError';


$ffi->type(opaque => 'Conn');
$ffi->type(opaque => 'Statement');
$ffi->type(opaque => 'Columns');


use Rust::mysql::Error;

Rust::mysql::Error->init_record_layout($ffi);
$ffi->type("record(Rust::mysql::Error)" => 'Error');


$ffi->attach( rust_mysql_conn_new => ['string', 'string', 'string', 'Error*'] => 'Conn' );
$ffi->attach( rust_mysql_conn_drop => ['Conn'] => 'void' );
$ffi->attach( rust_mysql_conn_prepare => ['Conn', 'string', 'Error*'] => 'Statement' );
$ffi->attach( rust_mysql_statement_columns => ['Statement'] => 'Columns' );
$ffi->attach( rust_mysql_columns_len => ['Columns'] => 'usize' );
$ffi->attach( rust_mysql_columns_names => ['Columns'] => 'string[]' );
$ffi->attach( rust_mysql_columns_drop => ['Columns'] => 'void' );
$ffi->attach( rust_mysql_statement_drop => ['Statement'] => 'void' );
$ffi->attach( rust_mysql_conn_start_transaction => ['Conn', 'Error*'] => 'bool' );
$ffi->attach( rust_mysql_conn_commit => ['Conn', 'Error*'] => 'bool' );
$ffi->attach( rust_mysql_conn_rollback => ['Conn', 'Error*'] => 'bool' );
$ffi->attach( rust_mysql_conn_in_txn => ['Conn'] => 'bool' );



push @{ $EXPORT_TAGS{all} }, 'rust_mysql_conn_new', 'rust_mysql_conn_drop', 'rust_mysql_conn_prepare', 'rust_mysql_statement_columns', 'rust_mysql_columns_len', 'rust_mysql_columns_names', 'rust_mysql_columns_drop', 'rust_mysql_statement_drop', 'rust_mysql_conn_start_transaction', 'rust_mysql_conn_commit', 'rust_mysql_conn_rollback', 'rust_mysql_conn_in_txn';

1; 